<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CAUNBGB" failures="2" tests="5" name="Test" time="48.902" errors="0" timestamp="2023-08-20T16:39:49 IST">
  <testcase classname="testCases.TC_03DataDrivenTest" name="DDtlogin" time="5.866">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_03DataDrivenTest.DDtlogin(TC_03DataDrivenTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDtlogin -->
  <testcase classname="testCases.TC_03DataDrivenTest" name="DDtlogin" time="6.964"/>
  <testcase classname="testCases.TC_03DataDrivenTest" name="DDtlogin" time="6.612"/>
  <testcase classname="testCases.TC_03DataDrivenTest" name="DDtlogin" time="7.5"/>
  <testcase classname="testCases.TC_03DataDrivenTest" name="DDtlogin" time="7.339">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_03DataDrivenTest.DDtlogin(TC_03DataDrivenTest.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- DDtlogin -->
</testsuite> <!-- Test -->
